---
defaultNamespace: fleet-poc

helm:
  releaseName: test-templating-works
  chart: oci://public.ecr.aws/isops/raw-helm-chart
  version: v0.0.1
  values:
    extraObjects:
      - apiVersion: v1
        data:
          CLUSTER_NAME: ${ .ClusterName }
        kind: ConfigMap
        metadata:
          name: test-templating-works

